name: CI/CD

on:
  push:
    branches:
      - feature/first

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Change directory
      run: cd ./core
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Install dependencies
      run: |
        go mod vendor

    - name: Run tests
      run: go test ./...
