name: CI/CD

on:
  push:
    branches:
      - feature/first

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install dependencies
      run: |
        cd ./core
        go mod vendor

    - name: Run tests
      run: |
        go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest
        cd ./core
        go test -json  -v ./... -coverprofile=../coverage.out 2>&1 | tee /tmp/gotest.log | gotestfmt -hide successful-tests,empty-packages
